import { onRequest } from "firebase-functions/v2/https";
import { setGlobalOptions } from "firebase-functions/v2/options";
import {
  getMyProfile,
  getUserDetail,
  listCommonCodes,
  listDepartments,
  listUsers,
  retireUser,
  searchUsers,
  sessionProfile,
  upsertProfile,
  upsertUserProfile,
} from "./profile.js";
import {
  approvalApproveDocument,
  approvalCreateDocument,
  approvalDeleteCustomLine,
  approvalDeleteTemp,
  approvalGetCustomLines,
  approvalGetDetail,
  approvalGetList,
  approvalGetSummary,
  approvalGetTempDetail,
  approvalGetTempList,
  approvalGetTemplates,
  approvalGetVacationBalance,
  approvalRejectDocument,
  approvalRetractDocument,
  approvalSaveCustomLine,
  approvalSaveTemp,
  approvalUpdateTemp,
} from "./approval.js";
import { createSelfRoom, markRoomRead, sendMessengerMessage } from "./messenger.js";
import {
  attendanceClockIn,
  attendanceClockOut,
  attendanceDepart,
  attendanceHistory,
  attendanceMonth,
  attendanceMonthList,
  attendanceToday,
  attendanceWeek,
  calendarCreateDept,
  calendarCreateUser,
  calendarDeleteDept,
  calendarDeleteUser,
  calendarGetEvents,
  calendarTeamProjects,
  calendarUpdateDept,
  calendarUpdateUser,
  communityGetList,
  dashboardAddFavoriteUser,
  dashboardFavoriteUsers,
  dashboardRemoveFavoriteUser,
  meetingCreateReservation,
  meetingCreateRoom,
  meetingDeleteReservation,
  meetingGetDetail,
  meetingGetReservations,
  meetingGetRooms,
  meetingUpdateReservation,
  projectCreate,
  projectCreateTask,
  projectDeleteTask,
  projectGetDetail,
  projectGetList,
  projectGetTasks,
  projectSetStatus,
  projectSetTaskStatus,
  projectUpdate,
  projectUpdateTask,
} from "./work.js";

setGlobalOptions({
  region: process.env.FUNCTION_REGION || "asia-northeast3",
  maxInstances: 10,
});

export const healthCheck = onRequest(async (_request, response) => {
  response.json({
    ok: true,
    service: "starworks-firebase",
    timestamp: new Date().toISOString(),
  });
});

export {
  sessionProfile,
  upsertProfile,
  listUsers,
  getUserDetail,
  getMyProfile,
  searchUsers,
  upsertUserProfile,
  retireUser,
  listDepartments,
  listCommonCodes,
  approvalGetTemplates,
  approvalGetSummary,
  approvalGetList,
  approvalGetDetail,
  approvalCreateDocument,
  approvalApproveDocument,
  approvalRejectDocument,
  approvalRetractDocument,
  approvalGetCustomLines,
  approvalSaveCustomLine,
  approvalDeleteCustomLine,
  approvalGetVacationBalance,
  approvalGetTempList,
  approvalGetTempDetail,
  approvalSaveTemp,
  approvalUpdateTemp,
  approvalDeleteTemp,
  createSelfRoom,
  sendMessengerMessage,
  markRoomRead,
  projectGetList,
  projectGetDetail,
  projectCreate,
  projectUpdate,
  projectSetStatus,
  projectGetTasks,
  projectCreateTask,
  projectUpdateTask,
  projectSetTaskStatus,
  projectDeleteTask,
  attendanceToday,
  attendanceHistory,
  attendanceClockIn,
  attendanceClockOut,
  attendanceWeek,
  attendanceMonth,
  attendanceMonthList,
  attendanceDepart,
  meetingGetRooms,
  meetingCreateRoom,
  meetingGetReservations,
  meetingGetDetail,
  meetingCreateReservation,
  meetingUpdateReservation,
  meetingDeleteReservation,
  calendarGetEvents,
  calendarCreateUser,
  calendarUpdateUser,
  calendarDeleteUser,
  calendarCreateDept,
  calendarUpdateDept,
  calendarDeleteDept,
  calendarTeamProjects,
  dashboardFavoriteUsers,
  dashboardAddFavoriteUser,
  dashboardRemoveFavoriteUser,
  communityGetList,
};
