query ListUserProfiles @auth(level: USER) {
  userProfiles {
    id
    firebaseUid
    userId
    userNm
    userEmail
    deptCd
    userRole
    workSttsCd
  }
}

query ListApprovalDocuments @auth(level: USER) {
  approvalDocuments {
    id
    docNo
    title
    statusCd
    draftedAt
    submittedAt
  }
}

query ListProjects @auth(level: USER) {
  projects {
    id
    projectNo
    projectName
    statusCd
    startedAt
    endedAt
  }
}
